version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - WEBHOOK_TUNNEL_URL=http://localhost:8080/
      - N8N_ENCRYPTION_KEY=7EDA4A16526FF8AE75EDA7100EF0E7A8C0E753D5
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_passwd
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=regular
      - EXECUTIONS_WORKER=queue
      - EXECUTIONS_WORKER_PROCESS=8
      - EXECUTIONS_WORKER_ACTIVE=2
      - QUEUE_BULL_REDIS_HOST=localhost
      - QUEUE_BULL_REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
  
  n8n-worker1:
    image: n8nio/n8n
    restart: always
    environment:
      - NODE_ENV=production
      # - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_WORKER=queue
      - EXECUTIONS_WORKER_PROCESS=4
      - EXECUTIONS_WORKER_ACTIVE=4
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - N8N_ENCRYPTION_KEY=7EDA4A16526FF8AE75EDA7100EF0E7A8C0E753D5
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_passwd
    links:
      - postgres
      - redis
    depends_on:
      - n8n
      - postgres
      - redis

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_passwd
      - POSTGRES_DB=n8ndb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7.2
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis_data:/data
volumes:
  n8n_data:
  postgres_data:
  redis_data:

