version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_ENCRYPTION_KEY=7EDA4A16526FF8AE75EDA7100EF0E7A8C0E753D5
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
      # - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_WORKER=queue
      - EXECUTIONS_WORKER_PROCESS=2
      - EXECUTIONS_WORKER_ACTIVE=2
      #REDIS VARIABLES
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
      - N8N_METRICS=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      #DATABASE ENV
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_passwd
      #NODE ENV
      - NODE_ENV=dev
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - postgres
    links:
      - postgres
      - redis


  n8n-worker1:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5679:5678"
    command: worker
    environment:
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_WORKER=queue
      - EXECUTIONS_WORKER_PROCESS=8
      - EXECUTIONS_WORKER_ACTIVE=8
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      #DATABASE ENV
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_passwd
    links:
      - postgres
      - redis
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  
  n8n-worker2:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5680:5678"
    command: worker
    environment:
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_WORKER=queue
      - EXECUTIONS_WORKER_PROCESS=8
      - EXECUTIONS_WORKER_ACTIVE=8
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      #DATABASE ENV
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_passwd
    links:
      - postgres
      - redis
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_passwd
      - POSTGRES_DB=n8ndb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U n8n_user -d n8n_passwd']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  n8n_data:
  postgres_data:
  redis_data:

